services:
  - type: web
    name: Stock-Bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: LINE_TOKEN
        sync: false
      - key: LINE_SECRET
        sync: false
      - key: SEARCH_API_KEY
        sync: false
      - key: SEARCH_ENGINE_ID
        sync: false
